name: CI/CD Pipeline application anybuddy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name:  Installation des dépendances
        run: npm install

      - name:  Vérification de Jest
        run: npm list jest || npm install --save-dev jest

      - name:  Exécution des tests
        run: npm test

      - name:  Build de l'application
        run: npm run build

      - name:  Déploiement (si tout est OK)
        if: success()
        run: echo "Déploiement en cours..."
